In [1]:
import torch
import numpy as np

In [2]:
t1 = torch.tensor(4)
print(t1)
print(t1.dtype)
print(t1.shape)

tensor(4)
torch.int64
torch.Size([])


In [3]:
t2 = torch.tensor(4.)
print(t2)
print(t2.shape)
print(t2.dtype)

tensor(4.)
torch.Size([])
torch.float32


In [4]:
# vector
t3 = torch.tensor([3.,1,2,5])
print(t3)
print(t3.dtype)
print(t3.shape)

tensor([3., 1., 2., 5.])
torch.float32
torch.Size([4])


In [5]:
# matrix
t4 = torch.tensor([[12,31],
                   [1,2]])
print(t4)
print(t4.dtype)
print(t4.shape)

tensor([[12, 31],
        [ 1,  2]])
torch.int64
torch.Size([2, 2])


In [6]:
# 3-dimensional array
t5 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
print(t5)
print(t5.shape)
print(t5.dtype)

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])
torch.Size([2, 2, 3])
torch.float32


In [7]:
# Basic Neuron (Perceptron)

x = torch.tensor(3)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad = True)

x,w,b

(tensor(3), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [8]:
# Arithmetic Operation

y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [9]:
# Compute Derivatives

y.backward()

In [10]:
# Display Derivatives

print(f"dx/dy: {x.grad}")
print(f"dw/dy: {w.grad}")
print(f"db/dy: {b.grad}")

dx/dy: None
dw/dy: 3.0
db/dy: 1.0


In [11]:
x = np.array([[1.,2.],[3.,4]])
print(f"x: {x}")
print(f"x.dtype: {x.dtype}")
print(f"x.shape: {x.shape}")

x: [[1. 2.]
 [3. 4.]]
x.dtype: float64
x.shape: (2, 2)


In [12]:
# Numpy to Tensor

y = torch.from_numpy(x)
print(f"y: {y}")
print(f"y.dtype: {y.dtype}")
print(f"y.shape: {y.shape}")

y: tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
y.dtype: torch.float64
y.shape: torch.Size([2, 2])


In [13]:
# Convert tensor to numpy

z = y.numpy()
print(f"z: {z}")
print(f"z.dtype: {z.dtype}")
print(f"z.shape: {z.shape}")

z: [[1. 2.]
 [3. 4.]]
z.dtype: float64
z.shape: (2, 2)
