In [1]:
import torch
import numpy as np

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

In [3]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])


In [4]:
print(inputs.shape)
print(targets.shape)

torch.Size([15, 3])
torch.Size([15, 2])


In [5]:
# Weights and Biases

w = torch.randn(3, 2, requires_grad = True)
b = torch.randn(2, requires_grad = True)
print(w)
print(b)

tensor([[-1.0334,  0.6178],
        [ 0.3470,  1.5134],
        [ 0.6589, -0.8890]], requires_grad=True)
tensor([0.0604, 0.7501], requires_grad=True)


In [6]:
def model(x):
    return torch.matmul(x,w) + b

In [7]:
# Genreate Prediciton

prediction = model(inputs)
print(f"predictions: {prediction}")

predictions: tensor([[-23.7946, 109.0203],
        [-21.2716, 133.2532],
        [ -5.1304, 205.7330],
        [-66.0430,  95.9480],
        [  8.1916, 126.4353],
        [-25.1749, 108.1246],
        [-20.9597, 130.8508],
        [ -5.5049, 205.4618],
        [-64.6627,  96.8437],
        [  9.8838, 124.9285],
        [-23.4827, 106.6179],
        [-22.6520, 132.3576],
        [ -5.4424, 208.1354],
        [-67.7353,  97.4548],
        [  9.5719, 127.3309]], grad_fn=<AddBackward0>)


In [8]:
print(f"targets: {targets}")

targets: tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])


In [9]:
error = targets - prediction
print(f"error: {error}")

error: tensor([[ 79.7946, -39.0203],
        [102.2716, -32.2532],
        [124.1304, -72.7330],
        [ 88.0430, -58.9480],
        [ 94.8084,  -7.4353],
        [ 82.1749, -39.1246],
        [100.9597, -28.8508],
        [123.5049, -73.4618],
        [ 85.6627, -58.8437],
        [ 94.1162,  -6.9285],
        [ 80.4827, -37.6179],
        [104.6520, -32.3576],
        [123.4424, -74.1354],
        [ 87.7353, -59.4548],
        [ 92.4281,  -7.3309]], grad_fn=<SubBackward0>)


In [10]:
# MSE
def mse_error(tar,pre):
    diff = tar - pre
    return torch.sum(diff * diff)/diff.numel()

In [11]:
mse_loss = mse_error(targets,prediction)
print(f"Mean Square Error: {mse_loss}")

Mean Square Error: 6015.94677734375


In [12]:
mse_loss.backward()

In [13]:
mse_loss

tensor(6015.9468, grad_fn=<DivBackward0>)

In [14]:
print(f"weight: {w}")
print(f"weight.grad: {w.grad}")

weight: tensor([[-1.0334,  0.6178],
        [ 0.3470,  1.5134],
        [ 0.6589, -0.8890]], requires_grad=True)
weight.grad: tensor([[-8280.4238,  3722.1189],
        [-8749.8359,  3680.7744],
        [-5413.8926,  2121.9004]])


In [15]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [16]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([0., 0.])


In [17]:
pred2 = model(inputs)
print(pred2)

tensor([[ -9.5586, 102.9242],
        [ -2.5707, 125.2685],
        [ 16.9393, 196.3314],
        [-51.8305,  89.7832],
        [ 26.0956, 118.8477],
        [-10.9436, 102.0281],
        [ -2.2922, 122.8817],
        [ 16.7018, 196.0018],
        [-50.4454,  90.6793],
        [ 27.7592, 117.3569],
        [ -9.2800, 100.5373],
        [ -3.9558, 124.3725],
        [ 16.6608, 198.7182],
        [-53.4941,  91.2740],
        [ 27.4806, 119.7438]], grad_fn=<AddBackward0>)


In [18]:
mse_loss2 = mse_error(targets, pred2)
print(f"MSE Error after 1 backprop: {mse_loss2}")

MSE Error after 1 backprop: 4137.326171875


In [19]:
for i in range(1,101):
    predi = model(inputs)
    mse_lossi = mse_error(targets, predi)
    mse_lossi.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
    print(f"Loss in epoch{i}: {mse_lossi}")

Loss in epoch1: 4137.326171875
Loss in epoch2: 2871.6171875
Loss in epoch3: 2018.748046875
Loss in epoch4: 1443.956298828125
Loss in epoch5: 1056.4703369140625
Loss in epoch6: 795.1495971679688
Loss in epoch7: 618.8126831054688
Loss in epoch8: 499.7199401855469
Loss in epoch9: 419.1878356933594
Loss in epoch10: 364.6311340332031
Loss in epoch11: 327.5732116699219
Loss in epoch12: 302.30438232421875
Loss in epoch13: 284.9787292480469
Loss in epoch14: 273.0059509277344
Loss in epoch15: 264.6407470703125
Loss in epoch16: 258.70806884765625
Loss in epoch17: 254.4163360595703
Loss in epoch18: 251.23199462890625
Loss in epoch19: 248.79603576660156
Loss in epoch20: 246.86642456054688
Loss in epoch21: 245.27999877929688
Loss in epoch22: 243.92727661132812
Loss in epoch23: 242.7338409423828
Loss in epoch24: 241.64993286132812
Loss in epoch25: 240.6420440673828
Loss in epoch26: 239.68759155273438
Loss in epoch27: 238.7711639404297
Loss in epoch28: 237.88223266601562
Loss in epoch29: 237.01412963

In [20]:
for i in range(1,101):
    predi = model(inputs)
    mse_lossi = mse_error(targets, predi)
    mse_lossi.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
    print(f"Loss in epoch{i}: {mse_lossi}")

Loss in epoch1: 189.66810607910156
Loss in epoch2: 189.150390625
Loss in epoch3: 188.6355438232422
Loss in epoch4: 188.12350463867188
Loss in epoch5: 187.6143341064453
Loss in epoch6: 187.10792541503906
Loss in epoch7: 186.6042938232422
Loss in epoch8: 186.1034393310547
Loss in epoch9: 185.60533142089844
Loss in epoch10: 185.10971069335938
Loss in epoch11: 184.61688232421875
Loss in epoch12: 184.1267547607422
Loss in epoch13: 183.63916015625
Loss in epoch14: 183.15414428710938
Loss in epoch15: 182.67156982421875
Loss in epoch16: 182.19158935546875
Loss in epoch17: 181.71417236328125
Loss in epoch18: 181.23919677734375
Loss in epoch19: 180.76654052734375
Loss in epoch20: 180.29647827148438
Loss in epoch21: 179.82884216308594
Loss in epoch22: 179.36354064941406
Loss in epoch23: 178.9005584716797
Loss in epoch24: 178.43991088867188
Loss in epoch25: 177.98158264160156
Loss in epoch26: 177.52552795410156
Loss in epoch27: 177.0717010498047
Loss in epoch28: 176.62020874023438
Loss in epoch29:

In [21]:
for i in range(1,101):
    predi = model(inputs)
    mse_lossi = mse_error(targets, predi)
    mse_lossi.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
    print(f"Loss in epoch{i}: {mse_lossi}")

Loss in epoch1: 148.52928161621094
Loss in epoch2: 148.19818115234375
Loss in epoch3: 147.86817932128906
Loss in epoch4: 147.539306640625
Loss in epoch5: 147.2115936279297
Loss in epoch6: 146.8850555419922
Loss in epoch7: 146.5597381591797
Loss in epoch8: 146.23538208007812
Loss in epoch9: 145.91224670410156
Loss in epoch10: 145.59014892578125
Loss in epoch11: 145.26927185058594
Loss in epoch12: 144.9493865966797
Loss in epoch13: 144.630615234375
Loss in epoch14: 144.31285095214844
Loss in epoch15: 143.9962921142578
Loss in epoch16: 143.68072509765625
Loss in epoch17: 143.36618041992188
Loss in epoch18: 143.05267333984375
Loss in epoch19: 142.7403106689453
Loss in epoch20: 142.42889404296875
Loss in epoch21: 142.11854553222656
Loss in epoch22: 141.80909729003906
Loss in epoch23: 141.50083923339844
Loss in epoch24: 141.1934356689453
Loss in epoch25: 140.88711547851562
Loss in epoch26: 140.58164978027344
Loss in epoch27: 140.27737426757812
Loss in epoch28: 139.9739532470703
Loss in epoch

In [22]:
for i in range(1,101):
    predi = model(inputs)
    mse_lossi = mse_error(targets, predi)
    mse_lossi.backward()
    with torch.no_grad():
        w -= w.grad * 1e-4
        b -= b.grad * 1e-4
        w.grad.zero_()
        b.grad.zero_()
    print(f"Loss in epoch{i}: {mse_lossi}")

Loss in epoch1: 120.08145141601562
Loss in epoch2: 117.63746643066406
Loss in epoch3: 115.25491333007812
Loss in epoch4: 112.93093872070312
Loss in epoch5: 110.66285705566406
Loss in epoch6: 108.44831085205078
Loss in epoch7: 106.2851791381836
Loss in epoch8: 104.17146301269531
Loss in epoch9: 102.10526275634766
Loss in epoch10: 100.08494567871094
Loss in epoch11: 98.10896301269531
Loss in epoch12: 96.17582702636719
Loss in epoch13: 94.2842788696289
Loss in epoch14: 92.43289947509766
Loss in epoch15: 90.62060546875
Loss in epoch16: 88.84635925292969
Loss in epoch17: 87.10907745361328
Loss in epoch18: 85.40766906738281
Loss in epoch19: 83.7413101196289
Loss in epoch20: 82.10904693603516
Loss in epoch21: 80.51001739501953
Loss in epoch22: 78.94347381591797
Loss in epoch23: 77.40865325927734
Loss in epoch24: 75.90479278564453
Loss in epoch25: 74.43115997314453
Loss in epoch26: 72.98709106445312
Loss in epoch27: 71.57195281982422
Loss in epoch28: 70.18506622314453
Loss in epoch29: 68.82581

In [23]:
for i in range(1,101):
    predi = model(inputs)
    mse_lossi = mse_error(targets, predi)
    mse_lossi.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
    print(f"Loss in epoch{i}: {mse_lossi}")

Loss in epoch1: 17.327722549438477
Loss in epoch2: 17.295698165893555
Loss in epoch3: 17.263702392578125
Loss in epoch4: 17.23175811767578
Loss in epoch5: 17.19991111755371
Loss in epoch6: 17.16811180114746
Loss in epoch7: 17.13639259338379
Loss in epoch8: 17.104692459106445
Loss in epoch9: 17.073078155517578
Loss in epoch10: 17.041561126708984
Loss in epoch11: 17.01005744934082
Loss in epoch12: 16.978633880615234
Loss in epoch13: 16.947254180908203
Loss in epoch14: 16.915971755981445
Loss in epoch15: 16.884716033935547
Loss in epoch16: 16.853540420532227
Loss in epoch17: 16.82244300842285
Loss in epoch18: 16.7913875579834
Loss in epoch19: 16.760387420654297
Loss in epoch20: 16.729450225830078
Loss in epoch21: 16.698577880859375
Loss in epoch22: 16.66777801513672
Loss in epoch23: 16.637004852294922
Loss in epoch24: 16.606327056884766
Loss in epoch25: 16.575708389282227
Loss in epoch26: 16.545143127441406
Loss in epoch27: 16.514619827270508
Loss in epoch28: 16.484172821044922
Loss in ep